menambahkan README.md
:\Users\LENOVO\SehatYuk>git push origin main
To https://github.com/oliporangsukses/SehatYuk.git
 ! [rejected]        main -> main (non-fast-forward)
 error: failed to push some refs to
 'https://github.com/oliporangsukses/SehatYuk.git'
 hint: Updates were rejected because a pushed branch tip is behind its
 remote
 hint: counterpart. If you want to integrate the remote changes, use
 'git pull'
 hint: before pushing again.
 menambahkan README.md

 # Conflicts:
 #       backend/index.js

 # Please enter the commit message for your changes. Lines starting
 # with '#' will be ignored, and an empty message aborts the commit.
 #
 # interactive rebase in progress; onto b8532ea
 # Last command done (1 command done):
 #    pick f824544 # menambahkan README.md
 # No commands remaining.
 # You are currently rebasing branch 'main' on 'b8532ea'.
 #
 # Changes to be committed:
 #       modified:   README.md
 #       modified:   backend/index.js
 #
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 ~
 .git/COMMIT_EDITMSG [unix] (20:48 11/04/2026)
 11,1 AllType  :qa  and press <Enter> to exit Vim